"Python 2.7":
  script:
  - "PY_EXE=python2.7 bash ./run-tests-for-ci.sh"
  tags:
  - python2.7
  except:
  - tags
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    CODECOV_TOKEN: "a0ed9aa4-e4d9-4b24-bf50-0d54e407bd92"

Python 3.5:
  script:
  - "PY_EXE=python3.5 bash ./run-tests-for-ci.sh"
  tags:
  - python3.5
  except:
  - tags
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    CODECOV_TOKEN: "a0ed9aa4-e4d9-4b24-bf50-0d54e407bd92"

Documentation:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - "cp local_settings.example.py local_settings.py"
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Mypy:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-mypy.sh
  - "cp local_settings.example.py local_settings.py"
  - ". ./prepare-and-run-mypy.sh"
  tags:
  - python3.5
  except:
  - tags

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh relate course accounts test bin"
  tags:
  - python3.5
  except:
  - tags
