language: python
cache: pip
install: true
matrix:
  include:
  - python: "2.7"
    env: RL_TRAVIS_TEST=test PY_EXE=python2.7
  - python: "3.5"
    env: RL_TRAVIS_TEST=test PY_EXE=python3.5
  - python: "3.6"
    env: RL_TRAVIS_TEST=cmdline PY_EXE=python3.6
  - python: "3.5"
    env: RL_TRAVIS_TEST=flake8 PY_EXE=python3.5
  - python: "3.6"
    env: RL_TRAVIS_TEST=mypy PY_EXE=python3.6
script:
  - bash ./run-travis-ci.sh
