jobs:
-
    job: 'Pytest'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python36:
                python.version: '3.6'
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            sudo apt-get install gettext
            PY_EXE=python3 bash ./run-tests-for-ci.sh

        displayName: 'Pytest'

    -
        task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test/pytest.xml'

-
    job: 'PytestExpensive'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python36:
                python.version: '3.6'
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            sudo apt-get install gettext
            PY_EXE=python3 RL_CI_TEST=test_expensive bash ./run-tests-for-ci.sh

        displayName: 'Pytest'

    -
        task: PublishTestResults@2
        inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'test/pytest.xml'

-
    job: 'Commandline'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            PY_EXE=python3 bash ./test-command-line-tool.sh python3

-
    job: 'Mypy'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-mypy.sh
            . ./prepare-and-run-mypy.sh python3 mypy==0.641

-
    job: 'Flake8'
    pool:
        vmImage: 'ubuntu-latest'
    strategy:
        matrix:
            Python37:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
            . ./prepare-and-run-flake8.sh relate course accounts tests bin
